#!/bin/bash
# srename

read -p "What's the name of the show?: " show
read -p "What Season of the show is this?: " s
read -p "Rename files in $PWD? (yes/no): " yn
while true; do
	case $yn in
		[Yy]* ){
			FILES=./*
			i=1
			for f in $FILES
			do
				mv "$f" "$show S$(printf %02d $s)E$(printf %02d $i).$(printf ${f##*.})"
				((i++))
			done
		};break;;
		[Nn]* ) exit;;
		* ) 	echo -n "Please respond 'yes' or 'no': ";;
	esac
done
